baseURL = "http://vavilen84.com/"
canonifyURLs = true

defaultContentLanguage = "en"

[languages]
[languages.en]
languageCode = "en-us"
weight = 0
title  = "Home"

[languages.ru]
languageCode = "ru-ru"
weight = 1
title = "Главная"

[taxonomies]
category = "categories"
tag = "tags"

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[outputs]
home = ["HTML", "JSON"]

[Params]
env = "prod"